### ISSUE TITLE
Nil pointer for PrometheusConfig.Skipper

### ISSUE THREAD

**Issue by limoli** [0neSe7en/echo-prometheus#1]
It misses a control at the following line:
```go
if config.Skipper(c) {
	return next(c)
}
```
It should be:
```go
if config.Skipper != nil && config.Skipper(c) {
	return next(c)
}
```

**Comment by 0neSe7en** [comment]
Thanks, good catch. I fixed it like this: https://github.com/labstack/echo/blob/master/middleware/cors.go#L69

**Comment by limoli** [comment]
Nice thank you! 👍
